### ISSUE TITLE
percentages should go above 100% unironically 

### ISSUE THREAD

**Issue by crazymonkyyy** [8dreams/8dreams.github.io#4]

**Comment by ukuleledanny** [comment]
Allow the two extreme answers to push it above 100%

**Comment by 8dreams** [comment]
It is possible. I saw some people go to levels from 100% to 110%.

**Comment by MedicineMelancholy0** [comment]
> Allow the two extreme answers to push it above 100%

they already do. i got over 100% on 2 of my axis
